# Generated by Django 2.0 on 2018-09-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('dateCreate', models.DateField(auto_now_add=True)),
                ('category', models.CharField(max_length=255)),
                ('music_file', models.FileField(blank=True, upload_to='static_files/music/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='static_files/cover/')),
            ],
        ),
    ]
