# Generated by Django 2.1 on 2018-09-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180909_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='pic',
            field=models.ImageField(blank=True, default='none_pic', null=True, upload_to='static_files/cover/'),
        ),
    ]
