# Generated by Django 2.1 on 2018-09-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180909_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='theme',
            field=models.CharField(default='rgb(157, 157, 157)', max_length=255),
        ),
    ]
