# Generated by Django 2.0 on 2018-09-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_music_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='theme',
        ),
        migrations.AddField(
            model_name='music',
            name='likes',
            field=models.IntegerField(default='0'),
        ),
    ]
