# Generated by Django 2.1 on 2018-09-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180917_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='duration',
            field=models.IntegerField(default='0'),
        ),
    ]
